// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sosa.Gym.Persistence.DataBase;

#nullable disable

namespace Sosa.Gym.Persistence.Migrations
{
    [DbContext(typeof(DataBaseService))]
    [Migration("20251106191936_Primera")]
    partial class Primera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sosa.Gym.Domain.Entidades.Ejercicio.EjercicioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaRutinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PesoUtilizado")
                        .HasColumnType("numeric");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<int>("Series")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiaRutinaId");

                    b.ToTable("Ejercicios", (string)null);
                });

            modelBuilder.Entity("Sosa.Gym.Domain.Entidades.Progreso.ProgresoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Brazos")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Cintura")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Pecho")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PesoActual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Piernas")
                        .HasColumnType("numeric");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Progresos", (string)null);
                });

            modelBuilder.Entity("Sosa.Gym.Domain.Entidades.Rutina.DiasRutinaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreDia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RutinaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RutinaId");

                    b.ToTable("DiasRutina", (string)null);
                });

            modelBuilder.Entity("Sosa.Gym.Domain.Entidades.Rutina.RutinaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Rutinas", (string)null);
                });

            modelBuilder.Entity("Sosa.Gym.Domain.Entidades.Usuario.UsuarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("numeric");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Sosa.Gym.Domain.Entidades.Ejercicio.EjercicioEntity", b =>
                {
                    b.HasOne("Sosa.Gym.Domain.Entidades.Rutina.DiasRutinaEntity", "DiasRutina")
                        .WithMany("Ejercicios")
                        .HasForeignKey("DiaRutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiasRutina");
                });

            modelBuilder.Entity("Sosa.Gym.Domain.Entidades.Progreso.ProgresoEntity", b =>
                {
                    b.HasOne("Sosa.Gym.Domain.Entidades.Usuario.UsuarioEntity", "Usuario")
                        .WithMany("Progresos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sosa.Gym.Domain.Entidades.Rutina.DiasRutinaEntity", b =>
                {
                    b.HasOne("Sosa.Gym.Domain.Entidades.Rutina.RutinaEntity", "Rutina")
                        .WithMany("DiasRutina")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("Sosa.Gym.Domain.Entidades.Rutina.RutinaEntity", b =>
                {
                    b.HasOne("Sosa.Gym.Domain.Entidades.Usuario.UsuarioEntity", "Usuario")
                        .WithMany("Rutinas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sosa.Gym.Domain.Entidades.Rutina.DiasRutinaEntity", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("Sosa.Gym.Domain.Entidades.Rutina.RutinaEntity", b =>
                {
                    b.Navigation("DiasRutina");
                });

            modelBuilder.Entity("Sosa.Gym.Domain.Entidades.Usuario.UsuarioEntity", b =>
                {
                    b.Navigation("Progresos");

                    b.Navigation("Rutinas");
                });
#pragma warning restore 612, 618
        }
    }
}
